robot_name: kinova_gen3

# Detector used to teleoperate the robot
detector:
  _target_: openteach.components.detector.oculus.OculusVRHandDetector
  host: ${host_address}
  oculus_port: ${oculus_reciever_port}
  keypoint_pub_port: ${keypoint_port}
  gripper_receiver_index_port: ${left_hand_receiver_port}
  gripper_receiver_grip_port: ${gripper_vr_grip}
  joystick_receiver_port: ${joystick_receiver_port}
  gripper_index_port: ${gripper_publish_port_left}
  gripper_grip_port: ${left_hand_receiver_port_two}
  wheelchair_port: ${wheelchair_port}
  button_port: ${resolution_button_port}
  button_publish_port: ${resolution_button_publish_port}
  teleop_reset_port: ${teleop_reset_port}
  teleop_reset_publish_port: ${teleop_reset_publish_port}
  tele_port: ${tele_port}
  tele_publish_port: ${tele_publish_port}
  home_port: ${home_port}
  home_pub_port: ${home_pub_port}


# Transformation classes used to transform the keypoints
transforms:
  - 
    _target_: openteach.components.detector.keypoint_transform.TransformHandPositionCoords
    host: ${host_address}
    keypoint_port: ${keypoint_port}
    transformation_port: ${transformed_position_keypoint_port}
    moving_average_limit: 1

# Visualizers used to visualize the keypoints stream
visualizers:
  -
    _target_: openteach.components.visualizers.visualizer_2d.Hand2DVisualizer
    host: ${host_address}
    transformed_keypoint_port: ${transformed_position_keypoint_port}
    oculus_feedback_port: ${oculus_graph_port}
    display_plot: ${visualize_right_2d}

# Operators used to retarget the keypoints
operators:
  - 
    _target_: openteach.components.operators.kinova_gen3.KinovaGen3Operator
    host: ${host_address}
    transformed_keypoints_port: ${transformed_position_keypoint_port}
    moving_average_limit: 1
    arm_resolution_port: ${resolution_button_publish_port}
    use_filter: True
    teleoperation_reset_port: ${teleop_reset_publish_port}
    gripper_index_port: ${gripper_publish_port_left}
    gripper_grip_port: ${left_hand_receiver_port_two}
    wheelchair_port: ${wheelchair_port}
    tele_gui_port: ${tele_publish_port}
    home_port: ${home_pub_port}

# List of controller classes used
controllers:
  -
    _target_: openteach.robot.kinova_gen3.KinovaGen3

recorded_data:
  - 
    - joint_states
    - cartesian_states
    - wheelchair_joy_commands
    - wheelchair_states
    - imu
